version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ["*"]
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ["*"]
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ["*"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ["*"]
