# This rule is not used by the project sample-external-issuer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over sample-issuer.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sample-external-issuer
    app.kubernetes.io/managed-by: kustomize
  name: sampleclusterissuer-admin-role
rules:
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers
  verbs:
  - '*'
- apiGroups:
  - sample-issuer.example.com
  resources:
  - sampleclusterissuers/status
  verbs:
  - get
