apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-sampleclusterissuer
spec:
  commonName: certificate-by-sampleclusterissuer.example.com
  secretName: certificate-by-sampleclusterissuer
  issuerRef:
    name: sampleclusterissuer-sample
    group: sample-issuer.example.com
    kind: SampleClusterIssuer
