apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-by-sampleissuer
spec:
  commonName: certificate-by-sampleissuer.example.com
  secretName: certificate-by-sampleissuer
  issuerRef:
    name: sampleissuer-sample
    group: sample-issuer.example.com
    kind: SampleIssuer
