apiVersion: sample-issuer.example.com/v1alpha1
kind: SampleIssuer
metadata:
  name: sampleissuer-sample
spec:
  authSecretName: "sampleissuer-sample-credentials"
  url: "http://sample-issuer.example.com/api/v1"
